=== nazih-amri/UML_Diagrams_Generator/UML Diagram Generator/resources/xml/project.dtd
<!ELEMENT project (name,package*,relations?)>
<!ELEMENT name (#PCDATA)>
<!ELEMENT package (class*,annotation*,interface*,enumeration*)>
<!ELEMENT relations (relation+)>
<!ELEMENT class (name,field*,constructor*,method*,relation*)>
<!ELEMENT annotation (name,method*)>
<!ELEMENT interface (name,field*,method*)>
<!ELEMENT enumeration (name,constant*)>
<!ELEMENT field EMPTY>
<!ELEMENT constructor (parameter*)>
<!ELEMENT method (parameter*)>
<!ELEMENT constant EMPTY>
<!-- <!ELEMENT relation (source,target)> -->
<!ELEMENT relation (target)>
<!ELEMENT source (#PCDATA)>
<!ELEMENT target (#PCDATA)>
<!ELEMENT parameter EMPTY>

<!ATTLIST project path CDATA #REQUIRED>
<!ATTLIST package name ID #REQUIRED>
<!ATTLIST class id ID #REQUIRED>
<!ATTLIST annotation id ID #REQUIRED>
<!ATTLIST interface id ID #REQUIRED>
<!ATTLIST enumeration id ID #REQUIRED>

<!ATTLIST field name CDATA #REQUIRED
				type CDATA #REQUIRED
				visibility CDATA #REQUIRED>
<!ATTLIST constructor name CDATA #REQUIRED
				visibility CDATA #REQUIRED>
<!ATTLIST method name CDATA #REQUIRED
				return-type CDATA #REQUIRED
				visibility CDATA #REQUIRED>
<!ATTLIST parameter type CDATA #REQUIRED>
<!ATTLIST relation type CDATA #REQUIRED>
<!ATTLIST constant name CDATA #REQUIRED>

=== nazih-amri/UML_Diagrams_Generator/UML Diagram Generator/resources/xml/project.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE project SYSTEM "project.dtd">
<project path="C:\Users\na-zi\OneDrive\Bureau\MQL_NAZIH_AMRI\S1\JAVA\p04-XML-Parsers">
    <name>p04-XML-Parsers</name>
    <package name="org.mql.java.xml">
        <class id="org.mql.java.xml.Examples">
            <name>Examples</name>
            <constructor name="org.mql.java.xml.Examples" visibility="public"/>
            <method name="exp01" return-type="void" visibility="public"/>
            <method name="exp4" return-type="void" visibility="public"/>
            <method name="exp5" return-type="void" visibility="public"/>
            <method name="exp3" return-type="void" visibility="public"/>
            <method name="exp6" return-type="void" visibility="public"/>
            <method name="exp02" return-type="void" visibility="public"/>
            <method name="main" return-type="void" visibility="public static">
                <parameter type="[Ljava.lang.String;"/>
            </method>
        </class>
        <annotation id="org.mql.java.xml.Annot1">
            <name>Annot1</name>
            <method name="name" return-type="String" visibility="public abstract"/>
        </annotation>
        <annotation id="org.mql.java.xml.Annotationn">
            <name>Annotationn</name>
            <method name="order" return-type="int" visibility="public abstract"/>
        </annotation>
        <interface id="org.mql.java.xml.Inter1">
            <name>Inter1</name>
            <field name="NAME" type="java.lang.String" visibility="public static final"/>
            <method name="getName" return-type="String" visibility="public abstract"/>
            <method name="setName" return-type="void" visibility="public abstract">
                <parameter type="java.lang.String"/>
            </method>
        </interface>
        <enumeration id="org.mql.java.xml.enum1">
            <name>enum1</name>
            <constant name="CONSTANT1"/>
            <constant name="CONSTANT2"/>
            <constant name="CONSTANT3"/>
        </enumeration>
    </package>
    <package name="org.mql.java.xml.dom">
        <class id="org.mql.java.xml.dom.AuthorsParser">
            <name>AuthorsParser</name>
            <constructor name="org.mql.java.xml.dom.AuthorsParser" visibility="public"/>
            <method name="parse" return-type="List" visibility="public">
                <parameter type="java.lang.String"/>
            </method>
        </class>
        <class id="org.mql.java.xml.dom.XMLNode">
            <name>XMLNode</name>
            <field name="node" type="org.w3c.dom.Node" visibility="private"/>
            <field name="children" type="org.mql.java.xml.dom.XMLNode[]" visibility="private"/>
            <constructor name="org.mql.java.xml.dom.XMLNode" visibility="public">
                <parameter type="java.lang.String"/>
            </constructor>
            <constructor name="org.mql.java.xml.dom.XMLNode" visibility="public">
                <parameter type="org.w3c.dom.Node"/>
            </constructor>
            <method name="getchild" return-type="XMLNode" visibility="public">
                <parameter type="java.lang.String"/>
            </method>
            <method name="getName" return-type="String" visibility="public"/>
            <method name="getValue" return-type="String" visibility="public"/>
            <method name="isNamed" return-type="boolean" visibility="public">
                <parameter type="java.lang.String"/>
            </method>
            <method name="getNode" return-type="Node" visibility="public"/>
            <method name="getAttribute" return-type="String" visibility="public">
                <parameter type="java.lang.String"/>
            </method>
            <method name="setNode" return-type="void" visibility="public">
                <parameter type="org.w3c.dom.Node"/>
            </method>
            <method name="getChildren" return-type="XMLNode[]" visibility="public"/>
            <method name="getIntAttribute" return-type="int" visibility="public">
                <parameter type="java.lang.String"/>
            </method>
            <method name="extractChildren" return-type="void" visibility="private"/>
        </class>
        <class id="org.mql.java.xml.dom.XMLNodeProf">
            <name>XMLNodeProf</name>
            <field name="node" type="org.w3c.dom.Node" visibility="private"/>
            <field name="children" type="org.mql.java.xml.dom.XMLNodeProf[]" visibility="private"/>
            <constructor name="org.mql.java.xml.dom.XMLNodeProf" visibility="public">
                <parameter type="java.lang.String"/>
            </constructor>
            <constructor name="org.mql.java.xml.dom.XMLNodeProf" visibility="public">
                <parameter type="org.w3c.dom.Node"/>
            </constructor>
            <method name="getName" return-type="String" visibility="public"/>
            <method name="getValue" return-type="String" visibility="public"/>
            <method name="isNamed" return-type="boolean" visibility="public">
                <parameter type="java.lang.String"/>
            </method>
            <method name="getNode" return-type="Node" visibility="public"/>
            <method name="getAttribute" return-type="String" visibility="public">
                <parameter type="java.lang.String"/>
            </method>
            <method name="setNode" return-type="void" visibility="public">
                <parameter type="org.w3c.dom.Node"/>
            </method>
            <method name="getChild" return-type="XMLNodeProf" visibility="public">
                <parameter type="java.lang.String"/>
            </method>
            <method name="getChildren" return-type="XMLNodeProf[]" visibility="public"/>
            <method name="getIntAttribute" return-type="int" visibility="public">
                <parameter type="java.lang.String"/>
            </method>
            <method name="extractChildren" return-type="void" visibility="private"/>
        </class>
    </package>
    <package name="org.mql.java.xml.models">
        <class id="org.mql.java.xml.models.Author">
            <name>Author</name>
            <field name="test" type="org.mql.java.xml.models.Test" visibility="private static final"/>
            <field name="id" type="int" visibility="private"/>
            <field name="name" type="java.lang.String" visibility="private"/>
            <field name="birthday" type="org.mql.java.xml.models.Date" visibility="private"/>
            <field name="country" type="java.lang.String" visibility="private"/>
            <field name="technology" type="java.lang.String" visibility="private"/>
            <constructor name="org.mql.java.xml.models.Author" visibility="public">
                <parameter type="int"/>
                <parameter type="java.lang.String"/>
                <parameter type="org.mql.java.xml.models.Date"/>
                <parameter type="java.lang.String"/>
                <parameter type="java.lang.String"/>
            </constructor>
            <method name="getTechnology" return-type="String" visibility="public"/>
            <method name="getName" return-type="String" visibility="public"/>
            <method name="toString" return-type="String" visibility="public"/>
            <method name="setName" return-type="void" visibility="public">
                <parameter type="java.lang.String"/>
            </method>
            <method name="getId" return-type="int" visibility="public"/>
            <method name="getCountry" return-type="String" visibility="public"/>
            <method name="setBirthday" return-type="void" visibility="public">
                <parameter type="org.mql.java.xml.models.Date"/>
            </method>
            <method name="getBirthday" return-type="Date" visibility="public"/>
            <method name="setTechnology" return-type="void" visibility="public">
                <parameter type="java.lang.String"/>
            </method>
            <method name="setId" return-type="void" visibility="public">
                <parameter type="int"/>
            </method>
            <method name="setCountry" return-type="void" visibility="public">
                <parameter type="java.lang.String"/>
            </method>
            <relation type="aggregation">
                <target>org.mql.java.xml.models.Date</target>
            </relation>
            <relation type="composition">
                <target>org.mql.java.xml.models.Test</target>
            </relation>
        </class>
        <class id="org.mql.java.xml.models.Child">
            <name>Child</name>
            <field name="name" type="java.lang.String" visibility="private"/>
            <field name="parent" type="org.mql.java.xml.models.Parent" visibility="private"/>
            <constructor name="org.mql.java.xml.models.Child" visibility="public">
                <parameter type="org.mql.java.xml.models.Parent"/>
                <parameter type="java.lang.String"/>
            </constructor>
            <method name="iamMethod" return-type="void" visibility="public"/>
            <method name="iamMethod3" return-type="void" visibility="public"/>
            <method name="iamMethod2" return-type="void" visibility="public"/>
            <method name="hello" return-type="void" visibility="public"/>
            <method name="hello2" return-type="void" visibility="public"/>
            <relation type="realization">
                <target>org.mql.java.xml.models.Hello</target>
            </relation>
            <relation type="realization">
                <target>org.mql.java.xml.models.Hello2</target>
            </relation>
            <relation type="realization">
                <target>java.io.Serializable</target>
            </relation>
            <relation type="aggregation">
                <target>org.mql.java.xml.models.Parent</target>
            </relation>
        </class>
